server:
  port: 8085

spring:
  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL11Dialect
#    init:
#      data-locations: classpath:data.sql,classpath:authors.sql
#      mode: always

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
