server:
  port: 8085

spring:
  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  security:
    user:
      name: admin
      password: 123
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    defer-datasource-initialization: false
  #
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL11Dialect
#  sql:
#    init:
#      mode: always

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
upload:
  path: D:/Spring modul/covers
download:
  path: D:/Spring modul/books-file