server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie
auth:
  secret: bulaukin
jwt:
  duration: 3000

spring:
  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  security:
    user:
      name: admin
      password: 123
    oauth2:
      client:
        registration:
          facebook:
            client-id: 5786346641451883
            client-secret: a9ea1ddcd820349c58e929ac20f9dd73
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 7001
  #    show-sql: true
#    defer-datasource-initialization: false
  #
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL11Dialect
#  sql:
#    init:
#      mode: always

  liquibase:
    enabled: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
upload:
  path: D:/Spring modul/covers
download:
  path: D:/Spring modul/books-file


